import type { OpsEntry } from "./types";

const byName = (a: OpsEntry, b: OpsEntry): number => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0);

const cell = (s: string | undefined): string => (s ? s.replace(/\|/g, "\\|").replace(/\r?\n/g, " ") : "—");

function table(header: string[], rows: string[][]): string {
  const lines = [`| ${header.join(" | ")} |`, `|${header.map(() => "---").join("|")}|`];
  for (const r of rows) lines.push(`| ${r.join(" | ")} |`);
  return lines.join("\n");
}

/**
 * Generate INDEX.md from the vm/project entries. Output is deterministic: sorted by name,
 * `\n` line endings, and the only date in it is the caller-supplied `generatedOn`.
 */
export function generateIndex(entries: OpsEntry[], generatedOn: string): string {
  const vms = entries.filter((e) => e.kind === "vm").sort(byName);
  const projects = entries.filter((e) => e.kind === "project").sort(byName);

  const vmRows = vms.map((vm) => {
    const hosted = projects.filter((p) => p.deployedOn.includes(vm.name)).map((p) => p.name);
    return [`[${vm.name}](${vm.path})`, cell(vm.detail), cell(vm.lastUpdated), cell(hosted.join(", "))];
  });
  const projectRows = projects.map((p) => [
    `[${p.name}](${p.path})`,
    cell(p.detail),
    cell(p.deployedOn.join(", ")),
    cell(p.lastUpdated),
  ]);

  const parts = [
    "# Ops Memory Index",
    "",
    "<!-- Auto-generated by Mochi. Do not edit by hand. -->",
    `Generated: ${generatedOn}`,
    "",
    `## VMs (${vms.length})`,
    "",
    vms.length ? table(["VM", "Provider", "Last updated", "Projects"], vmRows) : "_None yet._",
    "",
    `## Projects (${projects.length})`,
    "",
    projects.length ? table(["Project", "Repo", "Deployed on", "Last updated"], projectRows) : "_None yet._",
    "",
  ];
  return parts.join("\n");
}
